corrected and added comments

diff --git a/app/build/scripts/app b/app/build/scripts/app
--- a/app/build/scripts/app
+++ b/app/build/scripts/app
@@ -83,8 +83,7 @@ done
 # This is normally unused
 # shellcheck disable=SC2034
 APP_BASE_NAME=${0##*/}
-# Discard cd standard output in case $CDPATH is set (https://github.com/gradle/gradle/issues/25036)
-APP_HOME=$( cd "${APP_HOME:-./}.." > /dev/null && pwd -P ) || exit
+APP_HOME=$( cd "${APP_HOME:-./}.." && pwd -P ) || exit
 
 # Use the maximum available, or set MAX_FD != -1 to use that value.
 MAX_FD=maximum
@@ -112,7 +111,7 @@ case "$( uname )" in                #(
   NONSTOP* )        nonstop=true ;;
 esac
 
-CLASSPATH=$APP_HOME/lib/app.jar:$APP_HOME/lib/javafx-fxml-12-win.jar:$APP_HOME/lib/javafx-web-12-win.jar:$APP_HOME/lib/javafx-media-12-win.jar:$APP_HOME/lib/javafx-media-12.jar:$APP_HOME/lib/javafx-controls-12-win.jar:$APP_HOME/lib/javafx-controls-12.jar:$APP_HOME/lib/javafx-graphics-12-win.jar:$APP_HOME/lib/javafx-graphics-12.jar:$APP_HOME/lib/javafx-base-12-win.jar:$APP_HOME/lib/javafx-base-12.jar:$APP_HOME/lib/guava-31.1-jre.jar:$APP_HOME/lib/failureaccess-1.0.1.jar:$APP_HOME/lib/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar:$APP_HOME/lib/jsr305-3.0.2.jar:$APP_HOME/lib/checker-qual-3.12.0.jar:$APP_HOME/lib/error_prone_annotations-2.11.0.jar:$APP_HOME/lib/j2objc-annotations-1.3.jar
+CLASSPATH=$APP_HOME/lib/app.jar:$APP_HOME/lib/javafx-web-12-win.jar:$APP_HOME/lib/javafx-media-12-win.jar:$APP_HOME/lib/javafx-media-12.jar:$APP_HOME/lib/javafx-fxml-12-win.jar:$APP_HOME/lib/javafx-controls-12-win.jar:$APP_HOME/lib/javafx-controls-12.jar:$APP_HOME/lib/javafx-graphics-12-win.jar:$APP_HOME/lib/javafx-graphics-12.jar:$APP_HOME/lib/javafx-base-12-win.jar:$APP_HOME/lib/javafx-base-12.jar:$APP_HOME/lib/guava-31.1-jre.jar:$APP_HOME/lib/failureaccess-1.0.1.jar:$APP_HOME/lib/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar:$APP_HOME/lib/jsr305-3.0.2.jar:$APP_HOME/lib/checker-qual-3.12.0.jar:$APP_HOME/lib/error_prone_annotations-2.11.0.jar:$APP_HOME/lib/j2objc-annotations-1.3.jar
 
 
 # Determine the Java command to use to start the JVM.
@@ -131,13 +130,10 @@ location of your Java installation."
     fi
 else
     JAVACMD=java
-    if ! command -v java >/dev/null 2>&1
-    then
-        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
+    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
 
 Please set the JAVA_HOME variable in your environment to match the
 location of your Java installation."
-    fi
 fi
 
 # Increase the maximum file descriptors if we can.
